{% set name = "opyplus" %}
{% set version = "2.0.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/openergy/opyplus/archive/{{ version }}.tar.gz
  sha256: d71002752cbe366fb5ce780a5d3bd73c21ec0272eab695cec251aebdc4a2f9a1


build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pandas >=0.20.0,<2.0
    - unidecode >=1.0.22,<2.0
    - python-slugify >=3.0.2,<4.0
    - cchardet >=2.1.4,<3.0

test:
  imports:
    - opyplus

about:
  home: https://github.com/openergy/opyplus
  license: MPL-2.0
  license_family: MOZILLA
  license_file: LICENSE.txt
  summary: A package to work with EnergyPlus in python
  description: |
    opyplus is a python package is a package that can be used to work with EnergyPlus in Python. 
    More specifically, it allows to::
         Parse, query and modify idf files efficiently, with a number of checks ensuring that your idf file remains correct throughout your work
         Parse and create epw files
         Launch simulations on EnergyPlus
         Parse EnergyPlus output files
  doc_url: https://opyplus.readthedocs.io/
  dev_url: https://github.com/openergy/opyplus

extra:
  recipe-maintainers:
    - ccruveiller
    - geoffroy-destaintot
